spring:
  application:
    name: app
  flyway:
    enabled: true
    locations:
      - classpath:db/migration/resources
      - classpath:db/migration/booking
      - classpath:db/migration/payments
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
