spring:
  application:
    name: app
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
